apiVersion: v1
kind: Namespace
metadata:
  name: app
---
apiVersion: v1
kind: ResourceQuota
metadata:
  name: app-rs
  namespace: app
spec:
  hard:
    limits.cpu: "1"
    limits.memory: 1Gi
    requests.cpu: "1"
    requests.memory: 1Gi
    requests.nvidia.com/gpu: "0"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-app
  namespace: app
spec:
  selector:
    matchLabels:
      app: app
  replicas: 4
  template:
    metadata:
      labels:
        app: app
    spec:
      tolerations:
      - operator: Exists
      containers:
      - image: cargo.dev.caicloud.xyz/release/nginx:test2
        name: app
        ports:
        - containerPort: 80
        resources:
          limits:
            cpu: 100m
            memory: 100Mi
          requests:
            cpu: 50m
            memory: 50Mi
---
apiVersion: v1
kind: Service
metadata:
  name: app-service
  namespace: app
spec:
  selector:
    app: app
  ports:
  - name: default
    protocol: TCP
    port: 80
    targetPort: 80
